CREATE DATABASE FOOTBALL_DATA;
USE FOOTBALL_DATA;
CREATE SCHEMA FOOTBALL_DATA.RAW;

---- ## PREMIER LEAGUE EVENTS ## ----
CREATE OR REPLACE TABLE FOOTBALL_DATA.RAW.PREMIER_LEAGUE_EVENTS(
RAW_FILE VARIANT);
--  IT'S HIGHLY COMPRESSED, USED FOR SEMISTRUCTURED DATA, OPTIMIZES QUERYS IN  SNOWFLAKE. 

COPY INTO FOOTBALL_DATA.RAW.PREMIER_LEAGUE_EVENTS
  FROM @MANAGE_DB.EXTERNAL_STAGES.PREMIER_LEAGUE_EVENTS_STAGE_S3
  FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT
  ON_ERROR = SKIP_FILE;

SELECT * 
  FROM FOOTBALL_DATA.RAW.PREMIER_LEAGUE_EVENTS;